import Head from 'next/head'
import styles from '../styles/Home.module.css'

import GetToKnow from '../components/GetToKnow'
import Discover from '../components/Discover'
import Why from '../components/Why/Why'

export default function Home({ catsData }) {
  return (
    <div>
      <Head>
        <title>CatWiki App | Zaid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GetToKnow catsData={catsData} />
      <Discover />
      <Why />
    </div>
  )
}

// Fetches API data before Next generates the page
export async function getStaticProps() {
  const response = await fetch('https://api.thecatapi.com/v1/breeds?api_key=e3bd9ee7-02be-445a-966e-ad339d3a9ff8')

  const data = await response.json()

  // console.log('Data', data)
  return {
    props: {
      catsData: data
    }
  }
}
