import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'
import GetToKnow from '../components/GetToKnow'

export default function Home() {
  return (
    <div className="lg:px-24 md:px-16 sm:px-8 xxs:px-4">
      <Head>
        <title>zzz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <GetToKnow />
      </main>

    </div>
  )
}
